all:    counting_sort_test count_in_area


counting_sort_test: counting_sort_test.cc counting_sort.cc
    g++ -g -o counting_sort_test counting_sort_test.cc counting_sort.cc --std=c++1y

count_in_area:  8.2-4.cc
    g++ -g -o count_in_area 8.2-4.cc --std=c++1y
